import type { ReactNode } from 'react';

import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }): ReactNode => (
  <html lang="en" className="dark">
    <body className={`${inter.className} p-12 gap-12 flex flex-col w-4/5`}>
      {children}
    </body>
  </html>
);

export default RootLayout;
